### ISSUE TITLE
Codemod: Convert binary expression to ternary for style values

### ISSUE THREAD

**Issue by at-nathan** [atlassian-labs/compiled#1027]
**Is your feature request related to a problem? Please describe.**
Binary expressions are not support when evaluating style values, for example:

```
const Comp = styled.div`
  width: ${({ customWidth }) => customWidth && `${customWidth}px`};
`;
``` 
The binary expression here can return the value `false` which is invalid.

**Describe the solution you'd like**
We can help migration by adding functionality to component codemods to convert this to a ternary like:

```
const Comp = styled.div`
  width: ${({ customWidth }) => customWidth ? `${customWidth}px` : undefined};
`;
```

**Comment by pancaspe87** [comment]
Closing this ticket as we might want to just support binaries instead of having to code mod them
