### ISSUE TITLE
Codemod/cli is unable to find codemods

### ISSUE THREAD

**Issue by danieldelcore** [atlassian-labs/compiled#1071]
**Describe the bug**
Compiled default flow (no flags) is unable to find a codemod

**To Reproduce**

1. `npx @compiled/cli`
2. select `codemods`
3. Error

**Expected behavior**
The flow works as expected

![compiled-cli](https://user-images.githubusercontent.com/3030010/153305012-e4600eb9-b952-4c71-9a48-fc7e885dc49f.gif)

**Comment by pancaspe87** [comment]
Hi @danieldelcore,
thanks for taking the time to report the issue.
We'll add it in our backlog and try to address it as soon as we have capabilities.

**Comment by pancaspe87** [comment]
https://github.com/atlassian-labs/compiled/pull/1195 could be a potential workaround.

**Comment by danieldelcore** [comment]
Can confirm the workaround works 👍👍👍👍 Closing
