### ISSUE TITLE
Shadowed variables can clash with destructured props

### ISSUE THREAD

**Issue by pancaspe87** [atlassian-labs/compiled#1086]
Given this scenario:

```
const isPrimary = true;

const Component = styled.div<TextProps>`
  color: ${({ isPrimary }) => (isPrimary ? 'green' : 'red')};
  font-weight: ${() => (isPrimary ? 'bold' : undefined)};
`;
```
The outer scope `isPrimary` is taking precedence over the one used in the `color` arrow function, which is incorrect behaviour. 

It seems`color` is being statically evaluated, so it could be `evaluate-expression` is used the scope of the file to evaluate `isPrimary`.

**Comment by at-nathan** [comment]
The merged fix breaks conditional expressions containing binary expressions i.e.
```
width: ({ isOpen }) => isOpen ? `${spacing * 4}px` :  0,
```
