### ISSUE TITLE
CSS Parsing Exception: 

### ISSUE THREAD

**Issue by onionhammer** [atlassian-labs/compiled#1112]
**Describe the bug**
When compiling CSS after upgrading from @compiled/webpack-loader 0.8.0 to 0.8.3, I get the following error on build:

```
Input CSS: {

    border: none;
    outline: none;
    background: #fd5b47;
    color: #fff;
    user-select: none;
    text-align: center;
    text-decoration: none;
    text-transform: uppercase;1.4rem;
    font-size: ;;
    font-weight: 700;
    line-height: 1.4;
    transition: color .2s, background-color .2s;
    border-radius: 2rem;
    box-sizing: border-box;
    appearance: none;
    display: inline-block;;

    :hover, :focus {
        background: #f0a202;
    }

    :disabled, :hover:disabled {
        background: #cdd7d6;
    }
;
  }

  Exception: <css input>:9:31: Unknown word
    at runMicrotasks (<anonymous>)
```

with this source

![image](https://user-images.githubusercontent.com/969938/155735903-e738b8cb-66e5-4dc9-820d-b549a2e2be6d.png)

**Comment by onionhammer** [comment]
This occurs in 0.8.1 and 0.8.2, so something changed between 0.8.0 and 0.8.1 to break this

**Comment by pancaspe87** [comment]
Hi @onionhammer,
thanks for reporting the bug. 

In [@compiled/babel-plugin@0.13.0](https://github.com/atlassian-labs/compiled/releases/tag/%40compiled%2Fbabel-plugin%400.13.0) we released a fix for conditional rules. However, I didn't consider the scenario of having duplicate properties in the same block.

Any particular reason why font-size is declared twice? As a temporary fix I would suggest you to remove `font-size: 1.4rem;`

@MonicaOlejniczak , @JakeLane  do we support duplicate properties in the same block? If so, I think we need to change the logic in [here](https://github.com/atlassian-labs/compiled/blob/master/packages/babel-plugin/src/utils/manipulate-template-literal.ts#L137)

**Comment by pancaspe87** [comment]
Raise a PR

**Comment by onionhammer** [comment]
@pancaspe87 no, no reason that duplicate should be there
