### ISSUE TITLE
Doesn't compile styles in a `styled.ts` file

### ISSUE THREAD

**Issue by baj84** [atlassian-labs/compiled#1153]
Compiled throws an error when my styles are in a filename label `example.styled.ts` if I rename this to `example.styled.tsx` it starts working again.

My webpack setup seems correct, as I have followed the examples in compiled.

`webpack.config.js`
```
webpackConfig.module.rules = [
  {
    test: [/\.tsx?$/, /\.jsx?$/],
    use: [{
      loader: 'babel-loader',
    }, {
      loader: '@compiled/webpack-loader',
      options: {
        extract: extractCSS,
        extensions: [
          '.ts',
          '.tsx',
        ],
        babelPlugins: ['typescript'],
      },
    }]
  },
];
```

The error it produces for .ts files:
``` 
Unexpected token, expected "]" (51:13)
  49 |   ...props
  50 | }, ref) => <CC>
  51 |       <CS>{[_, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16]}</CS>
     |            ^
  52 |       <C {...props} style={{ ...style,
  53 |     "--_3ckbb9": ix(getColor(props)),
  54 |     "--_1bzsgna": ix(getHoverColor(props)),`

**Comment by JakeLane** [comment]
Hi @baj84, can you please try adding `.ts` to your babel-loader? The `extensions` configuration option only defines extensions that you can import mixins/styles from. This is due to a limitation which we are tracking in #1000

**Comment by baj84** [comment]
Thanks @JakeLane You can see that `.ts` are currently included in the babel-loader test regx ` test: [/\.tsx?$/, /\.jsx?$/]`

Even with an explicit regex the same error occurs: `test: /\.(js|jsx|ts|tsx)$/,`

**Comment by JakeLane** [comment]
Ah, I see! Apologies, I misread the regex.

In this case, it looks like there is some configuration transpiling your `.ts` files into `.tsx` as TypeScript [requires the extension](https://www.typescriptlang.org/docs/handbook/jsx.html). You probably need to change your `babel.config.json` to have [isTSX](https://babeljs.io/docs/en/babel-preset-typescript#istsx) as true. Something like:
```
{
  "presets": [
    ["@babel/preset-env", { "targets": { "node": "current" } }],
    ["@babel/preset-typescript", { "isTSX": true, "allExtensions": true }],
    ["@babel/preset-react", { "runtime": "automatic" }]
  ]
}
```

With a webpack config of:
```
{
  test: [/\.tsx?$/, /\.jsx?$/],
  use: [{
    loader: 'babel-loader',
  }, {
    loader: '@compiled/webpack-loader',
    options: {
      extract: extractCSS,
      extensions: [
        '.ts',
        '.tsx',
        '.jsx'
      ],
      babelPlugins: ['typescript'],
    },
  }]
}
```

If that doesn't work, could you please share your whole webpack and babel configs?

**Comment by baj84** [comment]
Thanks a lot @JakeLane - that fixed my issue.
