### ISSUE TITLE
Prop filtering on DOM elements does not work

### ISSUE THREAD

**Issue by JakeLane** [atlassian-labs/compiled#1260]
**Describe the bug**
When passing a prop to a styled component, the props can be forwarded to the DOM element.

**Expected behavior**
Props should only be forwarded to DOM elements if they are a DOM prop

**Screenshots**
<img width="972" alt="Screen Shot 2022-07-12 at 3 10 19 PM" src="https://user-images.githubusercontent.com/5213366/178613466-9a5a2a3b-c78f-44e5-802b-a8e997fd8f84.png">

**Comment by SukkaW** [comment]
IIRC the documentation says to use the prefix `$` to not pass the prop to the DOM element. Does it work?

**Comment by pancaspe87** [comment]
Hi @SukkaW was this mentioned in Compiled? I think it is styled-components that uses [transient props ](https://styled-components.com/docs/api#transient-props)
