### ISSUE TITLE
RFC: Static style analysis

### ISSUE THREAD

**Issue by madou** [atlassian-labs/compiled#132]
How dope would it be if we could have a single source of truth of what colors and stuff we are using?

We generate a json file that we can then use to make decisions or share code or something. Would this be useful?

Input:

```
const n100 = '#ccc';

styled.div`
  color: 'red';
  background-color: ${n100};
`;
```

Output:

```
{
  n100: '#ccc',
  invalid: [{ src: 'packages/component.tsxL24', value: 'red'  }]
}
```

Or something.

**Comment by gwyneplaine** [comment]
I think the inverse would also be useful
I'd love to be able to coerce how a particular variable is being used in my system. 

Are we using this particular token properly? 
Are there any magic values we're using over and over again that we can capture as a css-variable / token? 

(this is charles btw)

**Comment by madou** [comment]
hi charles this is michael

and yeah for sure - this is all about understanding token usage and seeing what cool stuff we could do with it :fingerguns:

**Comment by madou** [comment]
I'm closing this issue to clean up the issue list.
