### ISSUE TITLE
flex property expansion in CSS is handled incorrectly for flex-basis 0

### ISSUE THREAD

**Issue by dbachko** [atlassian-labs/compiled#1350]
**Describe the bug**
flex shorthands are not handled correctly and cause incorrect CSS.

**To Reproduce**

```js
css({
    flex: '1 1 0'
});
```

The flex property is dropped entirely.

**Expected behavior**
The flex property should be expanded into atomic rules correctly.

**Additional context**
Workaround is to add some unit, for example **px**

```js
css({
    flex: '1 1 0px'
});
```

**Comment by JakeLane** [comment]
Hey @dbachko, after looking at this it seems browser behaviour deviates from the spec here 🤕. I'll make it inline with the browser where the `0` is transformed to `0px`.
