### ISSUE TITLE
Webpack extraction experimental?

### ISSUE THREAD

**Issue by Brianzchen** [atlassian-labs/compiled#1483]
Hey @JakeLane how's it going my old friend. I'm looking into this library now, can you please tell me how experimental [css extraction](https://compiledcssinjs.com/docs/css-extraction-webpack) is?

![image](https://github.com/atlassian-labs/compiled/assets/12436524/b00dc811-a4a2-471a-a0cb-52d5af2d6588)

Can I confidently use this or you recommend holding off?

**Comment by JakeLane** [comment]
Hey @Brianzchen 👋 

Yeah I would say it's safe to use for sure. We've got some improvements to build performance we'd like to upstream soonish but I'd only recommend using Compiled in production at scale with extraction enabled.
