### ISSUE TITLE
Cannot compose styles at runtime

### ISSUE THREAD

**Issue by Brianzchen** [atlassian-labs/compiled#1488]
**Describe the bug**
I have a component like this
```
const A = ({ style ) => {
  return <div css={css({ ...style })}></div>
};

const B = () => {
  return (
    <A
      style={{ color: 'pink' }}
    />
  );
}
```

The styles don't render, and when I try to pass in `style={css({})}` into a component then use `css={style}` later I end up with a call stack error. It seems that compiled only works when the syntax of `css={css(...)}` are all in the same component.

I'm trying to create a component library that abstracts the underlying css framework from the consumer so that they can get a really clean API but it seems compiled doesn't support this.

Is this a known issue or just something compiled has intentionally chosen not to support?

**Comment by dddlr** [comment]
Hi @Brianzchen yeah you're right in that we don't support runtime styles with the `css` prop currently.

[`xcss`](https://atlassian.design/components/primitives/xcss/usage) might be similar to what you're doing, and so could be worth checking out

The call stack error that Compiled gives is probably not ideal - will make a ticket to replace this with a more descriptive error

**Comment by Brianzchen** [comment]
Drats! That's a shame, though as I was thinking about it over the weekend I realised what I'm asking for might be way too far fetched for a compile time framework without adding some sort of annotation to denote that it's used for styles. 

Thanks for the heads up @dddlr, I've opted to use something else more runtime based and will optimise in other ways
