### ISSUE TITLE
CSS Map has its output property types unexpectedly expanded at times

### ISSUE THREAD

**Issue by itsdouges** [atlassian-labs/compiled#1639]
**Describe the bug**

Sometimes properties on the output object are expanded to `string` unexpectedly. This affects passing values to XCSS prop that expect narrowed types.

**To Reproduce**

```tsx
import { cssMap } from '@compiled/react';

const stylesValidRoot = cssMap({
  primary: {
    color: 'var(--ds-text)',
    '&:hover': { color: 'var(--ds-text-hover)', background: 'var(--ds-surface-hover)' },
  },
});

stylesValidRoot.primary.['&:hover'].background // string
```

However if we define it as `backgroundColor` it stays narrowed:

```tsx
import { cssMap } from '@compiled/react';

const stylesValidRoot = cssMap({
  primary: {
    color: 'var(--ds-text)',
    '&:hover': { color: 'var(--ds-text-hover)', backgroundColor: 'var(--ds-surface-hover)' },
  },
});

stylesValidRoot.primary.['&:hover'].backgroundColor // 'var(--ds-surface-hover)'
```

**Expected behavior**

The property remains narrowed to `'var(--ds-surface-hover)'`.

**Additional context**

This was found during the strict typing refactor, see: 

https://github.com/atlassian-labs/compiled/pull/1636/files#diff-1d4b97255cb11e9b25307047d51c7f2c1d94052d4626cc8e19c410a8b0444788R299

**Comment by kylorhall-atlassian** [comment]
This bug goes away when removing the generic from `CSS.Properties` 
```diff
export default function cssMap<
-  TStyles extends Record<string, CSS.Properties<number | string> & WhitelistedSelector & ExtendedSelectors>
+  TStyles extends Record<string, CSS.Properties & WhitelistedSelector & ExtendedSelectors>
>(
```

Can't tell you why, not sure I really understand what `TLength` is doing in the [csstype package](https://github.com/frenic/csstype).
