### ISSUE TITLE
Types on `css={…}` don't block using the top-level object from `cssMap()` 

### ISSUE THREAD

**Issue by kylorhall-atlassian** [atlassian-labs/compiled#1642]
**Describe the bug**

There's no type protection when consuming `cssMap` incorrectly, meaning TypeScript will allow code that won't compile properly.

**To Reproduce**

For raw `cssMap`, jump into https://github.com/atlassian-labs/compiled/blob/master/packages/react/src/css-map/__tests__/index.test.tsx#L29 and remove `.danger`
```diff
-const Foo = () => <div css={styles.danger}>hello world</div>;
+const Foo = () => <div css={styles}>hello world</div>;
```

Same, for the strict version:
https://github.com/atlassian-labs/compiled/blob/f093635244ca5accecd5093013694084408be2f7/packages/react/src/create-strict-api/__tests__/index.test.tsx#L162

**Expected behavior**

These should both have a type error.

**Screenshots**

No error 😞 
<img width="640" alt="Screenshot 2024-03-07 at 11 53 13 AM" src="https://github.com/atlassian-labs/compiled/assets/136543114/7e708a9d-b55a-45a0-bf48-78b6a6d6e874">

**Comment by itsdouges** [comment]
Thanks for raising this!
