### ISSUE TITLE
RFC: React native bindings

### ISSUE THREAD

**Issue by madou** [atlassian-labs/compiled#195]
Is this possible? Does React Native use babel as well? Let's find out.

- Styled components entry point https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/native/index.js
- Emotion https://github.com/emotion-js/emotion/blob/master/packages/native/src/index.js

**Comment by ankeetmaini** [comment]
This would be super lit to have. One thing for both web + native.

**Comment by madou** [comment]
We will revisit this later - for now I'm going to close to reduce noise.
