### ISSUE TITLE
Babel plugin does not correctly handle React namespace import in TSX file

### ISSUE THREAD

**Issue by marcins** [atlassian-labs/compiled#218]
**Describe the bug**
The Babel transformer plugin does not correctly detect a React namespace import in a TSX file when using the `@babel/preset-typescript`.

**To Reproduce**
`index.tsx`:
```
import * as React from 'react';
import { styled } from '@compiled/css-in-js';

const Foo = styled.div`font-weight: bold`;
```
`babel.config.json`:
```
{
    "plugins": [
        "@compiled/babel-plugin-css-in-js"
    ],
    "presets": [
        "@babel/preset-typescript",
        "@babel/preset-react"
    ]
}
```

Run `yarn babel index.tsx`, a parse error will occur:
```
SyntaxError: /Users/mszczepanski/Work/playground/compiled-bug/index.tsx: Identifier 'React' has already been declared (1:19)

> 1 | import * as React from 'react';
    |                    ^
  2 | import { styled } from '@compiled/css-in-js';
```

It appears that the import is detected (since that just makes sure there's an import from `react`), but an import clause for `react` is blindly added even if `* as React` already exists. 

I'm guessing the fix will be to not execute this code if there's already an `* as React` `ImportSpecifier`: https://github.com/atlassian-labs/compiled-css-in-js/blob/224c703f47734c02664c4520e3624b103ee7bdd4/packages/ts-transform/src/utils/visit-source-file-ensure-default-react-import.tsx#L47-L56

**Comment by marcins** [comment]
So a really hacky fix is to add a condition like this to the `if` statement just before the code above (at line 40):
 
```ts
if (
      ts.isImportDeclaration(node) &&
      ts.isStringLiteral(node.moduleSpecifier) &&
      node.moduleSpecifier.text === constants.REACT_PACKAGE_NAME &&
      !(node.importClause?.namedBindings && ts.isNamespaceImport(node.importClause.namedBindings) && node.importClause.namedBindings.name.text === 'React')
    ) {
```

**Comment by madou** [comment]
want to throw up a PR?

**Comment by marcins** [comment]
If you're happy with the hacky fix I'm happy to clean it up slightly and make it a real fix :)

**Comment by madou** [comment]
this will be fixed during the babel re-write.
