### ISSUE TITLE
Simpler usage with ts-loader

### ISSUE THREAD

**Issue by blasterpistol** [atlassian-labs/compiled#223]
It's already works, no need additional setup, just notice about that somewhere in the docs 😎

```js
const transformer = require('@compiled/ts-transform-css-in-js').default
```

```js
{
  loader: 'ts-loader',
  options: {
    getCustomTransformers: program => ({
      before: [transformer(program)],
    }),
  },
}
```

**Comment by madou** [comment]
Hey! Very good point TBH 😄 - would you be interested in adding it to the README + docs? Sneaky PR 😉

**Comment by madou** [comment]
hello :) we're pivoting from ts transformers to babel to align internally at Atlassian. unfortunately ts transformers are no longer supported - however the ts transformer package will still exist.

if you're using webpack and want to come with us on our journey i'd suggest building your typescript with babel.

🙏
