### ISSUE TITLE
Vue3 support

### ISSUE THREAD

**Issue by regenrek** [atlassian-labs/compiled#224]
Hey,

I would like to know if there is any hint on how we can use @compiled with vue.js and typescript?

I'm getting 

![image](https://user-images.githubusercontent.com/5182020/85888724-73211680-b7ea-11ea-88e3-45849a7c1ceb.png)

```
import 'vue-tsx-support/enable-check'
import '@compiled/css-in-js'
import * as vca from 'vue-tsx-support/lib/vca'

export default vca.component({
  name: 'Button',
  setup () {
    return () => (
      <div css={{
        fontSize: 12
      }} />
    )
  }
})
```

EDIT 1: 

To support the `css` prop I needed to change the type definition

```
import { CssFunction } from '@compiled/css-in-js/dist/types'

declare module 'vue-tsx-support/types/dom' {
  interface HTMLAttributes {
    css?: CssFunction | CssFunction[];
  }
}
````

EDIT 2:

The error above vanished when I set `NODE_ENV` to production. Unfortunately the component doesn't compile if `css`is set.

EDIT 3:

Ok it seems that props object is empty

![image](https://user-images.githubusercontent.com/5182020/85894661-7968c000-b7f5-11ea-8504-5d73a13e9841.png)

**Comment by madou** [comment]
Hi! So there is a React component under the hood to manage moving styles to
the head of the document. We'd have to figure out how to get that working
in Vue (or at least coming up with a Vue variant of the component I think)

**Comment by hc-codersatlas** [comment]
Would be good to support Vue 3 if there's any Vue support (especially with the new composition api). Better than rewriting it again later.

**Comment by madou** [comment]
currently there aren't any plans on the immediate roadmap to support vue - when the codebase is in a more mature state we'd definitely be interested with community contribution while giving any support needed.

**Comment by madou** [comment]
For now we are closing this issue but would consider adding Vue support with community support.
