### ISSUE TITLE
Bug in migrating docs

### ISSUE THREAD

**Issue by bradleyayers** [atlassian-labs/compiled#237]
On https://compiledcssinjs.com/docs/migrating at the bottom the snippet:

```ts
const getBackgroundGradient = (color, percent) => ({
  `linear-gradient(${color}, ${color}) 0 / ${percent}% 100% no-repeat
      ${color}`,
});
```

I think this perhaps should be:

```ts
const getBackgroundGradient = (color, percent) =>
  `linear-gradient(${color}, ${color}) 0 / ${percent}% 100% no-repeat
      ${color}`;
```

I'm not sure if this is the best place to raise this, I couldn't find the docs repo.

**Comment by madou** [comment]
Thanks! You can raise a PR here: https://github.com/compiled/website

**Comment by madou** [comment]
Moving into https://github.com/atlassian-labs/compiled/issues/284
