### ISSUE TITLE
Doc bugs

### ISSUE THREAD

**Issue by jantimon** [atlassian-labs/compiled#238]
@madou mentioned compiled on twitter and I had to checkout your work :)

Thanks already for the library - the ecosystem is really in need for a solution like yours.

I saw several tiny issues:

<img width="643" alt="404" src="https://user-images.githubusercontent.com/4113649/90731784-70164400-e2ca-11ea-9efb-b367eb9eb7ce.png">

<img width="561" alt="security" src="https://user-images.githubusercontent.com/4113649/90731933-a48a0000-e2ca-11ea-8ada-5df29d0b32d1.png">

<img width="523" alt="burger" src="https://user-images.githubusercontent.com/4113649/90732056-ce432700-e2ca-11ea-9563-a00a249e17c3.png">

Maybe some additional questions which were unclear to me when reading the docs:

1.  `__webpack_nonce__` - why is an attacker not able to use `__webpack__nonce__` to bypass csp?
2. is it possible to use human readable selectors?
3. is it possible to extract the css to a file?
4. is there a way to prefix hashes/css-variables?
5. is it possible to configure postcss?

**Comment by madou** [comment]
Hi! Thanks for taking the time to post an issue. 

Looks like you're correct with the docs comments! Ee can get them fixed up soon. If you're feeling up to it you can throw a PR up here: https://github.com/compiled/website

To answer your questions:

1. The premise here is it's up to your bundler to do something with the value. In this case webpack can replace it with something else. If I'm honest I haven't investigated too in depth with it right now - but ideally for every page load you'd have a randomly generated nonce.
2. Not at the moment - but will be config eventually to name selectors based on the component theyve been defined in.
3. Not at the moment - however it's on the roadmap. You will be able to extract to a single, atomic style sheet. 
4. Not at the moment.
5. Not at the moment - but it's on the roadmap

**Comment by jantimon** [comment]
I also created a small project which runs lighthouse tests for different css-in-js solutions - maybe we could also add compiled there: https://jantimon.github.io/css-framework-performance/

**Comment by madou** [comment]
Moving into https://github.com/atlassian-labs/compiled/issues/284
