### ISSUE TITLE
Shims for emotion and sytled components

### ISSUE THREAD

**Issue by hc-codersatlas** [atlassian-labs/compiled#254]
Hi, instead of a migration guide with a somewhat different syntax, would it be possible to have exact shims like for like so that it could be replaced by changing the dependencies and/or aliasing them e.g. in webpack? Would definitely help large codebases in migrating.

**Comment by madou** [comment]
hey mate!

migration is the biggest priority (outside of performance) for Atlassian - so it's very important for us to be able to do is both safely, and incrementally.

the API will closely match styled components & emotion (which are the two biggest CSS in JS libraries used internally). the biggest difference is dynamic runtime CSS won't work.

from there we'll have codemods for doing the heavy lifting - and for the most part it will end up just changing import declarations to point to the new package.

if you have other questions let us know.
