### ISSUE TITLE
Remove hardcoded 'styled' check for 'local.name'

### ISSUE THREAD

**Issue by pgmanutd** [atlassian-labs/compiled#256]
Replace `local.name` with `imported.name` [here](https://github.com/atlassian-labs/compiled/blob/023d2f5afefa659a7ab0787af1ea0ab648f3a89f/packages/babel-plugin/src/index.tsx#L20). 

Why? because when codemoded, original code

`import styledFunction from '@emotion/styled';` 

will be converted to

`import { styled as styledFunction } from '@compiled/css-in-js';`

Please think of other scenarios we can have here.

**Comment by madou** [comment]
raised here https://github.com/atlassian-labs/compiled/pull/261
