### ISSUE TITLE
RFC: Library name change

### ISSUE THREAD

**Issue by madou** [atlassian-labs/compiled#265]
![image](https://user-images.githubusercontent.com/6801309/91648989-e88eb900-eab1-11ea-8211-97b6ef2b5ea6.png)

So "Compiled CSS in JS" was always a placeholder name until we decided on a name. And then we shortened it to "Compiled" because it's quicker to say. Compiled doesn't really get the "what is this library" across quickly though.

If a better name existed, what would it be?

1. Needs to be a memorable name
1. Ideally gets the main point of the library across (style, bake, extract)

---

Themes

- Baked in styles
- Extracting styles
- Atomic CSS
- Styling
- CSS
- React
- JavaScript

Words

- Baked
- Style
- Atomic
- Extract
- CSS
- Static

---

- atomi
- atomicss
- atomistyle
- atomistyles
- atomake
- statomic
- atomex
- bakex
- sbex
- stylebex
- stylebakex
- cookex
- statistyle
- statstyle
- ssttyyllee
- stylic

Help!

**Comment by gwyneplaine** [comment]
Hey Siri, synonyms for built-in:

connatural: belonging naturally; innate.
connaturalCSS 
connatural-styles

unsheathedCSS 
integralCSS
fittedCSS
intrinsicCSS

**Comment by leocaseiro** [comment]
How about Cimota CSS which is atomic reversed?
`Array.from('atomic').reverse().join('')`

**Comment by chybisov** [comment]
How about **stylic**?

**Comment by madou** [comment]
> charles things here

@gwyneplaine they are a bit long IMO

> How about Cimota CSS which is atomic reversed?

it's a bit cryptic 🤔 

> stylic

short and sweet - i like it!

**Comment by leocaseiro** [comment]
Stylic is nice, I liked too, but I think it's taken on https://www.npmjs.com/package/stylic

**Comment by madou** [comment]
thats ok i got the npm org :)

**Comment by madou** [comment]
current short list:

- atomi
- stylic
- atomex
- distyl

still thinking.

**Comment by madou** [comment]
Thanks everyone involved, we will take this away and think it over.
