### ISSUE TITLE
Expand shorthand rules to long form rules

### ISSUE THREAD

**Issue by madou** [atlassian-labs/compiled#296]
This should be a new PostCSS plugin that gets ran before the atomic plugin. This shouldn't expand every  shorthand - only ones that would make sense to override. Be pragmatic.

**In**

```css
margin: 0 auto;
```

**Out**

```css
margin-top: 0;
margin-bottom: 0;
margin-left: auto;
margin-right: auto;
```

**Links/prior art**

- https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties
- https://github.com/kripod/css-shorthand-expanders
- https://github.com/kapetan/css-shorthand-expand
- https://github.com/modulz/stitches/blob/canary/packages/core/src/shorthand-parser/index.ts
- https://github.com/ChromeDevTools/devtools-frontend/blob/e11be3c4ad0438fda453a7179a601b9f74ffada0/front_end/sdk/CSSMetadata.js

**Comment by TxHawks** [comment]
There is [this](https://www.npmjs.com/package/postcss-shorthand-expand), though it's not complete
