### ISSUE TITLE
FS cache for module traversal

### ISSUE THREAD

**Issue by pgmanutd** [atlassian-labs/compiled#297]
This depends on #292 

Once PR #294 is merged, pick this one up.

**What to do**
- Read cache from files (during initialization phase) and save into in memory `this._cache`
- When adding new key to in memory `this._cache`, again save it back to file cache
- When accessing frequently used cached values, again save in memory `this._cache` back to file cache

Check [this comment](https://github.com/atlassian-labs/compiled/pull/294#issue-489270461) which explains how file caches will look like.

**Update:** We will cache based on file modification time instead of module code. Check [this comment](https://github.com/atlassian-labs/compiled/pull/294#issuecomment-696198197).

**Comment by madou** [comment]
I'm closing this issue to clean up the issue list.
