### ISSUE TITLE
Is there any equivalent to keyframes?

### ISSUE THREAD

**Issue by butlersrepos** [atlassian-labs/compiled#306]
SC and Emotion have straight forward mechanisms for declaring animations alongside their components (https://emotion.sh/docs/keyframes, https://styled-components.com/docs/basics#animations) is there such a thing in @compiled yet or how would you suggest adding animations to any @compiled components we have?

**Comment by madou** [comment]
Hi! The same keyframes API will be introduced towards the end of the year

For now you can write your own keyframes by just inlining it in a CSS prop/styled component

```
css={{
  '@keyframes my-anim': {
    from: {}
    to: {}
  }
}}
```
