### ISSUE TITLE
Will this support dynamic whole CSS property entries?

### ISSUE THREAD

**Issue by butlersrepos** [atlassian-labs/compiled#307]
Ex.
```

import { styled } from '@compiled/css-in-js';

const Foo = styled.div`
  ${(props) => (props.on ? 'color: red;' : 'color: black;')}
`
```

Today, this throws a
```
@parcel/transformer-babel: <css input>:3:3: Unknown word
          CssSyntaxError: <css input>:3:3: Unknown word
```

I would provide a codesandbox but I've had a hard time getting @compiled running in any, is there a starter template in codesandbox? .

**Comment by madou** [comment]
Hi,

At the moment that CSS won't be able to defined like that (so alternatively
define it as just the value and it will work).

I have some ideas how we can enable this though (because it's still static)
but we have other priorities at the moment.

We should add a better error message for this case!

**Comment by madou** [comment]
If you do

color: props => props.on ? 'black' : 'red'

It will work.

**Comment by pgmanutd** [comment]
@butlersrepos: Also check this link on compiled website: https://compiledcssinjs.com/docs/migrating#generating-css-at-runtime

**Comment by butlersrepos** [comment]
@pgmanutd Aha! I think your example in this context made it click for me, is it because 
```color: ${props => props.on ? 'blue' : 'red'}``` 
allows compiled to use css variables for optimal efficiency? 🤔

**Comment by madou** [comment]
yeah exactly - that and no runtime css is actually possible. in your original case the library considers that runtime CSS - however if we squint it's not really - so there may be opportunity to unwind it.

however - it would be low down the priority list for now 😄
