### ISSUE TITLE
Responsive dynamic values

### ISSUE THREAD

**Issue by TxHawks** [atlassian-labs/compiled#312]
**Is your feature request related to a problem? Please describe.**
When creating reusable components, it is often desirable to expose an api allowing the consumer to extend or change some aspects of the component's styles.

Dynamic definition of values are great, but they leave the common common use case of needing different values on different breakpoints difficult to handle.

For instance, with a reusable icon component, it would be quite common for the design team to want it in different sizes at different breakpoints.

**Describe the solution you'd like**
#165 discusses compile time responsive values, which could possibly allow this:

```ts
options: {
  media: {
    small: 400,
    medium: 800,
    large: 1000
  }
}

const Example = styled.div<{size: string || [ string, string, string, string ]}>`
  height: ${props => props.size},
  width: ${props => props.size},
`;
```

**Describe alternatives you've considered**
Another option would be to handle this manually, but that's a much more verbose API:

```ts
const Example = styled.div<{size: [ string, string, string, string ]}>`
  height: ${props => props.size[0]},
  width: ${props => props.size[0]},

  @media screen and (something) {
    height: ${props => props.size[1]},
    width: ${props => props.size[1]},
  }

  @media screen and (somethingElse) {
    height: ${props => props.size[2]},
    width: ${props => props.size[2]},
  }
`;
```

**Comment by madou** [comment]
Thanks for raising this @TxHawks - definitely agreed this is something we need. after the first release of the updated library we'll be prioritizing soemthing around this.

When it comes to ergonomics, I'm not sure how this would work if you're not using TypeScript. For example take the same code - what's to say we don't just want to access a value in an array passed in as props? Currently that generic is only for passed props.

Thinking through the general premise there are a few things that open up to us:

1. Enable media shorthands by configuration

```js
options: {
  media: {
    small: 400,
    medium: 800,
    large: 1000
  }
}
```

2. Access them through static CSS.

Easy enough, pretty obvious to use.

```js
height: [10px, 30px];
```

3. Access them through dynamic CSS

A bit boilerplatey, but it works and can be easily inferred as to what we should be doing here.

```js
styled.div<{ height: [number, number, number, number] }>`
  height: [${prop => props.height[0]}, ${prop => props.height[1]}];
`

<div 
  css={{
    height: [height[0], height[1]],
  }}
/>
```

What do you think?

**Comment by pgmanutd** [comment]
@madou: Also check [facepaint](https://github.com/emotion-js/facepaint) once and see if we can take something out of it.

**Comment by TxHawks** [comment]
Like I mentioned in #165, I think an object form of this would make intent clearer, even without Typescript.

A more significant question in my opinion is if there is any way in a compiled world to have a reusable component with a variadic prop signature like:

```ts
const Box = styled.div<{ height: number | [number, number, number, number] }>`
  height: ${prop => props.height};
`
```

Which will only have media queries in the generated code when needed:

```tsx
<Box height={4} /> {/* => { height: 4px; } */}
<Box height={[ 4, 6, 8, 10, ]} /> {/* => {
 height: 4px; 

 @media 1 { height: 6px;  }
 @media 2 { height: 8px;  }
 @media 3 { height: 10px;  }
} */} 
```

This should be easy enough to achieve with static styles, I don't see how it can be done with dynamic styles in a compiled world.

If I'm correct in assuming this will be impossible, people should be warned that exposing responsive dynamic APIs could end up generating quite a lot of unneeded code and should be used in moderation.

In many case, rules do not need to be truly dynamic in the runtime sense of it. A second, perhaps more viable pattern could just be composing styled components, which gives a lot of the same flexibility while remaining statically analyzable. It's more boilerplatey though:

```tsx
const Thing = styled.div`
   // ...
`;

const MyResponsiveThing = styled(Thing)`
 height: 4px; 

 @media 1 { height: 6px;  }
 @media 2 { height: 8px;  }
 @media 3 { height: 10px;  }
`
```

With responsive dynamic props only reserved for when you truly need  runtime dynamic props to be responsive, which I think is rare.

**Comment by madou** [comment]
I'm closing this issue to clean up the issue list as this is unlikely to be implemented in the short to medium term. If anyone has other thoughts or information we encourage you to comment on this issue.
