### ISSUE TITLE
CSS mixin api

### ISSUE THREAD

**Issue by gajus** [atlassian-labs/compiled#313]
**Is your feature request related to a problem? Please describe.**

CSS syntax highlighting is built based on premise that CSS code is wrapped with `css` tagged template literal. Without the tag syntax highlighting does not work.

<img width="303" alt="Screen Shot 2020-10-10 at 12 05 42 AM" src="https://user-images.githubusercontent.com/973543/95646272-628c6780-0a8c-11eb-8797-8c41c428e01f.png">
<img width="265" alt="Screen Shot 2020-10-10 at 12 05 47 AM" src="https://user-images.githubusercontent.com/973543/95646273-6324fe00-0a8c-11eb-86c1-d73e4ac4df56.png">

**Describe the solution you'd like**

Even if there is no use case for it, provide a dummy `css` tagged template literal that could be used simply to enable compatibility with the existing code editors, e.g.

```jsx
import {
  css,
  styled,
} from '@compiled/css-in-js';

const mixin = css`
  font-size: 12px;
`;

<div
  css={css`
    ${mixin};
    color: red;
  `}
/>

<div
  css={[mixin, { color: 'red' }]}
/>
```

To produce this CSS:

```css
font-size: 12px;
color: red;
```

---

**Testing notes**

- Used inline in a CSS prop
- Used in a local variable
- Used from a import
- Used in CSS prop array
- Dynamic CSS interpolations
- Static CSS interpolations

**Comment by madou** [comment]
hi - thanks for raising this!

this is on the roadmap - so it will be introduced eventually. just lower down the priority list ATM 😄 i'll keep this open to track it.

**Comment by sonatard** [comment]
Do you haave a plan to support arguments in the CSS String literal?

```tsx
const mixin = css(size)`
  font-size: ${size};
`;
```

Ref: CSS Object supports arguments.
https://github.com/atlassian-labs/compiled/pull/476

**Comment by madou** [comment]
No at the moment - is this something that emotion or styled components support?

**Comment by sonatard** [comment]
> No at the moment - is this something that emotion or styled components support?

I looked into it, but it doesn't support by styled-component and emotion. Also I think #341 feature supports by Compiled only. That's why I commented in Compiled, not in emotion. I think #341 so cool. 

I'll open issue it. And I would like to explain why I need it.

**Comment by sonatard** [comment]
I'm sorry that I was wrong. I wrote the code with emotion and checked it.

emotion support following codes.

```tsx
// 1. 
const color = (color: CSSProperties["color"]) => ({
  color,
});
```

```tsx
// 2. return css string literal
const color = (color: CSSProperties["color"]) => {
  return css`
    color: ${color};
  `;
};
```

If #341 will merge to main branch then Compilled support`2. return css string literal`. I don't need `3.  get arguments css function`.

```
// 3.  get arguments css function
const mixin = css(size)`
  font-size: ${size};
`;
```

**Comment by madou** [comment]
Ah okay

Yeah 1. and 2. will be supported when #341 is merged 

You also don't need to wait for #313 - for now you can just return a template literal that is "CSS like", e.g:

```tsx
const mixin = () => `color: blue;`;

<div css={mixin()} />
```

And it should work 👍

**Comment by sonatard** [comment]
That's good!! I'm looking forward to it. If #341 will be merged, I will Introduce Compiled in Japan.
And Congratulations! 1000 Stars! 
I was waiting for Atomic CSS by stylex from last year, but they were never released by Facebook. I was excited when I found Compiled.

**Comment by pgmanutd** [comment]
Cool @sonatard. Thanks for that. We will merge #341 asap. Your contributions are always welcome. 😃 ❤️
