### ISSUE TITLE
Setup rennovate

### ISSUE THREAD

**Issue by madou** [atlassian-labs/compiled#322]
Configure rennovate to run against this repo. Ideally it should be raise + merge automatically if all tests pass, for minor and patch updates.

For major - leave them open.

See: https://github.com/renovatebot/renovate

**Comment by jdanil** [comment]
Hi @madou. I recently did a dive into setting up renovate, so I'm happy to help out.
I think the app needs to be added at the github org level though, so not sure who would have access to do that.
https://docs.renovatebot.com/install-github-app/
Once the app is given access to this repo, it will raise a PR with some initial configuration.

For the behaviour you want, I think the config would look something like this.

```json
{
  "extends": ["group:monorepos", "group:recommended", "workarounds:all"],
  "lockFileMaintenance": {
    "enabled": true
  },
  "packageRules": [
    {
      "managers": ["npm"],
      "updateTypes": ["minor", "patch"],
      "automerge": true
    },
    {
      "managers": ["nvm"],
      "automerge": true
    },
    {
      "updateTypes": ["lockFileMaintenance"],
      "automerge": true
    }
  ],
  "postUpdateOptions": ["yarnDedupeHighest"],
  "rangeStrategy": "auto"
}
```

This will raise package updates that are often released together (e.g. react, react-dom, react-test-renderer, react-is, etc.) as a single pull request.
I also enabled lockfile maintenance which will try to regen the lockfile once a week, to update transitive dependencies.
Its also configured to dedupe dependencies after an update.
These changes will be automerged if status checks pass.
`separateMajorMinor` is true by default, so major updates will be raised in a separate PR and wont be automerged.

I think for github actions, you've tagged them with major version only in your workflow files, so I think they will already use new minor and patch versions, and renovate should only raise a PR when a new major version is released.

**Comment by madou** [comment]
Thanks! I've requested the rennovate app.

Awesome insight thanks! Will see what happens when its approved and we can get something working.

**Comment by madou** [comment]
Cheers I've set it up here, let's see how it goes https://github.com/atlassian-labs/compiled/pull/428

**Comment by jdanil** [comment]
I noticed that the pull requests aren't automerging. It looks like its because the repo requires pull request reviews.
It looks like there is a bot that can be added to automatically approve renovate pull requests.
https://docs.renovatebot.com/automerge-configuration/#required-pull-request-reviews

**Comment by madou** [comment]
thanks! I've set that up but it hasn't approved the already existing ones. maybe for new PRs?

**Comment by rarkins** [comment]
It only approves new PRs

**Comment by madou** [comment]
Thanks @rarkins!

Now I need to figure out why some major bumps haven't happened. Would have thought tsnode would be bumped.

**Comment by rarkins** [comment]
I suggest first enabling dependencyDashboard to get some visibility into planned PRs to confirm. Next, check the logs via app.renovatebot.com - find the "packages with updates" log message and then locate the dependency name within.

**Comment by madou** [comment]
That's very helpful, thanks
