### ISSUE TITLE
Magic numbers across the codebase

### ISSUE THREAD

**Issue by DarkPurple141** [atlassian-labs/compiled#330]
The comment in the header explains the use, but wondering if this may cause a regression in the future?

See for example: https://github.com/atlassian-labs/compiled/blob/1cc849c3ada6df3321c486ac4db92a9e6f0638a0/packages/runtime/src/ax.tsx#L35

**Comment by madou** [comment]
hey alex 😄 

a regression is unlikely because there are a _lot_ of tests around this behaviour, but we could definitely do better at commenting the code so it's easier to digest? (or were you thinking of something else?)

want to throw up a PR to name all the values?

**Comment by DarkPurple141** [comment]
Cool, cool. Yeah this was just something I noticed browsing the codebase to help get myself up to speed. I'm sure there are lots of processes in place to prevent such a regression.

In the case above I was just drawn to the `95` and `5` after reading the header comment given both do have some actual semantic meaning in the code. It could be an issue of inline commenting although I don't think that's a huge deal if you read the header comment.

Up to you philosophically if you want the magicNumbers made into variables. If yes, happy to comb codebase and adjust as appropriate.

**Comment by madou** [comment]
Yeah sure man! As long as it doesn't increase the bundle size should be
great! If it does, then perhaps we can lean on inline comments

**Comment by madou** [comment]
we've commented the `ax` util in our latest change
