### ISSUE TITLE
Add `css` back using a codemod

### ISSUE THREAD

**Issue by pgmanutd** [atlassian-labs/compiled#340]
When we fix #313, we might need to add back `css`. Add a codemod for it.

_Originally posted by @madou in https://github.com/atlassian-labs/compiled/pull/337#discussion_r516263130_

_Originally posted by @pgmanutd in https://github.com/atlassian-labs/compiled/pull/337#discussion_r516418329_

**Comment by madou** [comment]
Consolidated into #313
