### ISSUE TITLE
Modifying values outside of a module doesn't update the component styles

### ISSUE THREAD

**Issue by madou** [atlassian-labs/compiled#344]
**Describe the bug**

When developing (using Parcel) in a component and modifying some properties outside of the module that are imported - don't end up recompiling the component - thus they don't get updated.

```jsx
// colors.tsx
export const heroBackground = 'linear-gradient(120deg,blue 0%, #8fd3f4 100%)';

// hero.tsx
import React from 'react';
import '@compiled/core';
import { heroBackground } from '../utils/colors';

export const Hero = ({ children }: { children: React.ReactNode }) => {
  return (
    <div
      css={{
        background: heroBackground,
      }}>
      {children}
    </div>
  );
};
```

What's worse - sometimes you get into a state where it just won't update. In this case is it our caching behaviour, or is it the bundler? Both?

**To Reproduce**

1. Use code above
1. Run with your favourite bundler
1. Update hero background
1. Notice that the component doesn't have the updated color
1. Now modify hero component
1. Notice that is now is updated as expected

**Expected behavior**

It should update the component color without needing the modify the component file.

**Additional context**

Not sure what we can do here. Is it possible to fix this if we create a bundler plugin to make sure any depending module gets re-transformed if something changes?

**Questions**

- Does this also affect Webpack
- How can we force a bundler to recompile a consuming module (so it runs the Babel plugin over it, again)

**Comment by asvny** [comment]
Is there any workaround for this? seem like a blocker to me or could you care to explain what is the typical workflow to use compiled? like how to access theme, variants, etc..,

**Comment by madou** [comment]
It's a complicated one.

I've found if you also update the consuming component it does update, but it is unneeded friction, especially if you're iterating on those common files.

What happens if you disable Parcel's cache? `--no-cache` https://parceljs.org/cli.html

**Comment by asvny** [comment]
Both approaches don't seem to work in Parcel and Webpack. 😭

**Comment by madou** [comment]
To fix this in Webpack we'll most likely need to create a loader (plugin) and use this API https://webpack.js.org/api/loaders/#thisadddependency

Unsure about Parcel atm - @wbinnssmith do you know of any similar API in Parcel?

**Comment by madou** [comment]
I found this in Parcel https://github.com/parcel-bundler/parcel/blob/49ac217507d5914a2e38ca402593d26527cdb673/packages/core/core/src/public/Asset.js#L273

Related maybe?

**Comment by madou** [comment]
https://github.com/callstack/parcel-plugin-linaria/blob/master/src/LinariaAsset.js is a good example for Parcel 1, irrelvant for Parcel 2 however

`asset.addIncludedFile` seems to be what we're interested in but it's not working for me. Will start a discussion.

**Comment by madou** [comment]
Confirmed `addIncludedFile` is what we're interested in https://github.com/parcel-bundler/parcel/discussions/5677

**Comment by madou** [comment]
Hi all the webpack loader for Compiled is nearing completion, see: https://github.com/atlassian-labs/compiled/pull/530

If I cut a nightly would anyone want to have a play? Or alternatively grab the branch and play locally?
