### ISSUE TITLE
Test with new jsx automatic transform

### ISSUE THREAD

**Issue by madou** [atlassian-labs/compiled#349]
Currently unsure if we need to do anything to make it work.

**Comment by karlhorky** [comment]
You will need to use [`@jsxImportSource`](https://babeljs.io/docs/en/babel-plugin-transform-react-jsx#customizing-the-automatic-runtime-import) instead of `@jsx` and `@jsxFrag`.

Also, if you don't have the following exports, then you will need them:

- `jsx`
- `jsxs`
- `jsxDEV`
- `createElement`

Source: https://github.com/emotion-js/emotion/pull/1970

**Comment by madou** [comment]
hi @karlhorky - interestingly we don't actually use a custom jsx pragma - so the theory is we won't have to do much to get it working.

still need to test soon though! 😄

**Comment by karlhorky** [comment]
Ah nice, good to hear! Best of luck!

**Comment by karlhorky** [comment]
Wonder if these things will still be needed for TypeScript support (the [`jsxImportSource`](https://www.typescriptlang.org/tsconfig#jsxImportSource) option for the new transform released in TS 4.1), since TS won't be able to benefit from the Compiled Babel plugin...

**Comment by madou** [comment]
Hi, what are we talking about? 🙂

When using Babel it doesn't really matter what your setting is for JSX because TSC isn't used to compiled your code.

**Comment by karlhorky** [comment]
For sure - I'm thinking of other situations such as when TS tries to figure out the JSX transform and comes across the unknown `css` prop, which it will complain about - eg. I've had this issue with the Emotion CSS prop before (also using a Babel plugin), and needed to configure `jsxImportSource` in `tsconfig.json`.

**Comment by madou** [comment]
hmm yeah that's a good point - we could definitely have that problem 😅 

will take inspiration from emotion for their solution later when it comes up.
