### ISSUE TITLE
SSR checks in runtime are using old window check

### ISSUE THREAD

**Issue by MatthewCharlton** [atlassian-labs/compiled#353]
**Is your feature request related to a problem? Please describe.**

Currently in the Server Provider https://github.com/atlassian-labs/compiled/blob/master/packages/runtime/src/provider/provider-server.tsx#L4 the check to see if window is "undefined" can fail if consumers use more exotic forms of Server Side Rendering that emulate a browser environment.

**Describe the solution you'd like**

I propose exporting a function in which consumers can pass in a predicate which returns true when being Server Side Rendered. Giving consumers more flexibility with the technology they use to Server Side Render their apps.
Something like:
```
// index.js
import { isSSR } from @compiled/core;
import App from './App';
isSSR(() => !(window && window.navigator));
export default () => <App />;
```
Compiled would then use the returned value of this function as the source of truth for all SSR related code branches.

**Comment by madou** [comment]
hi thanks for  raising this

this is something that hasn't been moved over to the new logic, oops! 

we use a `isNodeEnvironment` function now to do this (see: https://github.com/atlassian-labs/compiled/blob/master/packages/runtime/src/provider/index.tsx#L4 and https://github.com/atlassian-labs/compiled/blob/master/packages/runtime/src/is-node.tsx) 

we generate two bundles

1. browser bundle (sourced through `browser` field in package json)
2. isomorphic bundle (sourced through `main` field in package json)

the browser bundle removes all server code from the bundle to keep the bundle size small 👍 

would you be interested putting up a PR to replace any cases of `typeof window` with the new `isNodeEnvironment` check?

**Comment by MatthewCharlton** [comment]
Sure

**Comment by MatthewCharlton** [comment]
Using the `isNodeEnvironment` function will work for most use cases but what if someone were using `Deno`, or any other server side JavaScript environment?

**Comment by madou** [comment]
only node is supported at this time 😄
