### ISSUE TITLE
Re-release library

### ISSUE THREAD

**Issue by madou** [atlassian-labs/compiled#362]
- [x] Rename `core` to `react` https://github.com/atlassian-labs/compiled/pull/363
- [x] Merge updated README https://github.com/atlassian-labs/compiled/pull/356
- [x] Cut `minor` version
- [x] Merge updated docs site https://github.com/compiled/compiled-website/pull/11

**Comment by madou** [comment]
Done!

**Comment by pgmanutd** [comment]
> Done!

Hurray Hurrayyyyyy 🎉 Hurrrayyy!! 😄 😄
