### ISSUE TITLE
Conditional CSS rules for styled

### ISSUE THREAD

**Issue by madou** [atlassian-labs/compiled#390]
We've implemented conditional logical expressions in #379. We now need to add support to `styled` apis.

```js
styled.div`
  color: 'blue';
  ${props => props.isPrimary && ({ color: 'red' })};
`;

styled.div(
  { color: 'blue' },
  props => props.isPrimary && ({ color: 'red' }),
);

styled.span`
  color: ${(props) => (props.primary ? '#00B8D9' : '#36B37E')};
`;
```

Conditional template literal CSS is blocked by #313 - atm the CSS builder code assumes if we are returning a template literal we are returning a CSS declaration, not a CSS rule.

**Comment by Kelin2025** [comment]
Double thank you for someone who's doing this. The lack of this feature is the reason why I didn't switch to Linaria and stay with styled-components  
Question - will it put inline expression into a component or it guesses what the function will return? 
I mean, will it also support something like this:
```ts
const Button = styled.button`
  ${props => ({
    normal: { padding: "20px", fontSize: "16px" },
    large: { padding: "40px", fontSize: "32px" }
  })[props.$size]}
`
```
Or just ternary operators only?
