### ISSUE TITLE
React package babel plugin entry point has main and module in package.json reversed

### ISSUE THREAD

**Issue by KoharaKazuya** [atlassian-labs/compiled#482]
**Describe the bug**
https://github.com/atlassian-labs/compiled/blob/8908a402de570f98054e45b0233a7c9233af1fbc/packages/react/babel-plugin/package.json#L2-L3

If I understand correctly, `main` should be common js (cjs) and `module` should be ES module (esm). Is it just a mistake?

**Comment by madou** [comment]
hi! yeah looks like a mistake. amusingly both end up resolving to common js however - so it's not really affecting anything (we don't assume ESM for node environments).

want to put up a fix? would be a nice first contribution 🥳

**Comment by pgmanutd** [comment]
oops. Thanks @KoharaKazuya for raising this.
