### ISSUE TITLE
postcss-values-parser@4.0.0 license issue

### ISSUE THREAD

**Issue by pgmanutd** [atlassian-labs/compiled#484]
Latest version of Switcher has `@atlaskit/lozenge` bumped to `10.1.0` - this pulls in `@compiled/react` which itself pulls in `postcss-values-parser@4.0.0`. The problem with this is the license for that library is incompatible (MPL-2.0) and its breaking Confluence FE pipeline.

@madou: If you are around. Do take a look at this. I am investigating how `postcss-values-parser@4.0.0` end up in the deps.

**Comment by madou** [comment]
Oh interesting. I'm out right now so I can't look but it's because the
babel plugin is included in the react package.

**Comment by pgmanutd** [comment]
No worries. Let me see how it goes. And any alternative we can find.

**Comment by pgmanutd** [comment]
So,`@compiled/react` depends on `@compiled/babel-plugin` which in turns depends on `@compiled/css` and confluence pipeline is going all way down to check `dependency` keyword for all these packages in `yarn.lock` file. 

AF `yarn.lock` has this:

```
"@compiled/css@0.5.1":
  version "0.5.1"
  resolved "https://packages.atlassian.com/api/npm/npm-remote/@compiled/css/-/css-0.5.1.tgz#af597612a38ba777b9c574d1e3ed1bd10bcc90c2"
  integrity sha1-r1l2EqOLp3e5xXTR4+0b0QvMkMI=
  dependencies:
    "@compiled/utils" "0.5.1"
    autoprefixer "^9.7.6"
    convert-source-map "^1.7.0"
    cssnano-preset-default "^4.0.7"
    postcss "^7.0.27"
    postcss-nested "^4.2.1"
    postcss-normalize-whitespace "^4.0.2"
    postcss-selector-parser "^6.0.2"
    postcss-values-parser "^4.0.0"
```

Might be an issue with Confluence like how they are checking the license of these packages. They should check license for packages which are actually shipped I think. Anyways, for now they are whitelisting this in confluence frontend.

Lets keep this open, and see if there is an alternative for `postcss-values-parser`, if we really need it. Not sure.

**Comment by pgmanutd** [comment]
I think I get it. Since `@compiled/react` is actual package which is shipped along with runtime. And we have direct dependency (not dev one) of `@compiled/babel-plugin` under it. Might be confluence going way down it to check license for all the dependencies. Do we need to separate `@compiled/babel-plugin` from `@compiled/react`? 🤔

**Comment by madou** [comment]
Yep.

Looking at the packages license: https://github.com/shellscape/postcss-values-parser/issues/115

They won't change it to MIT.

If this is a problem we'll need to find an alternative - we could potentially roll our own if needed and can't find an alternative.

**Comment by madou** [comment]
I've found this https://www.npmjs.com/package/postcss-value-parser

It's more used and is also MIT license. Let's move to that.

**Comment by pgmanutd** [comment]
> Yep.
> 
> Looking at the packages license: [shellscape/postcss-values-parser#115](https://github.com/shellscape/postcss-values-parser/issues/115) - they won't change it to MIT.
> 
> If this is a problem we'll need to find an alternative - we could potentially roll our own if needed and can't find an alternative.
> 
> What tool are we using to test licenses? We should probably turn it on here.

We are using [solicitorio](https://bitbucket.org/atlassian/solicitorio). But I am not sure what all licenses **Confluence FE** is checking for. Acc. to **solicitorio** docs, one can define licenses in `.solicitoriorc` file:

```
{
  "compatibleLicenses": [
      "MIT",
      "Apache",
      "Apache-2.0",
      "BSD",
      "BSDv3",
      "WTFPL",
      "CC0-1.0",
      "CC-BY-3.0"
  ],
  "warningLicenses": [
      "ISC",
      "Unlicense"
  ],
  "whiteListedModules": [
      "normalize-package-data@1.0.3",
  ]
}
```

**Comment by pgmanutd** [comment]
> I've found this https://www.npmjs.com/package/postcss-value-parser
> 
> It's more used and is also MIT license. We should spike to see how hard it will be to move to it.
> 
> Edit: Some of our transitive dependencies also use `postcss-values-parser` - if we replace it it'll still be installed. Would that prove fruitless if we replace it, then? Do we also need to replace all transitive deps using it?

Nah..that will be hard. So problem boils down to the case where `@compiled/react` has `@compiled/babel-plugin` under `dependencies` key and not `devDependencies`. I think **solicitorio** is checking `dependencies` key for all the dependent packages until it hit the dead end. Under the hood **solicitorio** is using (npm-license-crawler)[https://github.com/mwittig/npm-license-crawler].

**Comment by pgmanutd** [comment]
Should we integrate [solicitorio](https://bitbucket.org/atlassian/solicitorio) in our pipeline? Can be a good first issue 😄 
We might need list of license we have to support and packages we are whitelisting.

**Comment by madou** [comment]
yeah might as well

**Comment by pgmanutd** [comment]
Can you get mandatory license list which Confluence, JIRA and bitbucket are using? I don't have access 😞

**Comment by madou** [comment]
Will look tmr

**Comment by pgmanutd** [comment]
> Will look tmr

No rush 😄
