### ISSUE TITLE
Conditional array CSS prop type errors

### ISSUE THREAD

**Issue by sonatard** [atlassian-labs/compiled#489]
**Describe the bug**

The following code got TypeScript error.
https://compiledcssinjs.com/docs/css-prop#conditional-rules

```
TS2322: Type 'false | { border: string; color: string; }' is not assignable to type 'string | number | void | CSSProps | AnyKeyCssProps<void>'.   Type 'boolean' is not assignable to type 'string | number | void | CSSProps | AnyKeyCssProps<void>'.
```

**Expected behavior**
No errors.

**Screenshots**
<img width="771" alt="error" src="https://user-images.githubusercontent.com/1586910/104141269-353bb680-53f9-11eb-9912-dd25403e7cb9.png">

**Desktop (please complete the following information):**

- OS: macOS BigSir 11.1
- Browser Google Chrome
- Version 87.0.4280.141（Official Build） （x86_64）

**Develop Environment**

- TypeScript: 4.1.3
- @compiled/react: 0.5.2

**Comment by madou** [comment]
thanks for raising, what version of `@compiled/react` are you using? what version of TS are you using? do you have a repo replicating this?

**Comment by sonatard** [comment]
Update TypeScript and @compiled/react version. I'm preparing repository.  Please just a moment.

**Comment by sonatard** [comment]
I created a sample repository here 👍 
https://github.com/sonatard/compiled

**Comment by madou** [comment]
Thanks! I've replicated the bug. The types don't support that - I'll put in a fix for you.

As a quick work around you can `@ts-ignore` the lines of code.

**Comment by pgmanutd** [comment]
@sonatard: And ternary is not supported at the moment. Its already in the [pipeline](https://github.com/atlassian-labs/compiled/issues/389).

Otherwise something like this might worked:

```ts
isPrimary ? { color: 'red' } : undefined
```
