### ISSUE TITLE
No codemods available right now

### ISSUE THREAD

**Issue by alexreardon** [atlassian-labs/compiled#490]
When running `npx @compiled/cli@latest` or `npx @compiled/cli --preset codemods` I am getting the following error:

> No codemods available right now.

I have already followed the installation steps here: https://compiledcssinjs.com/docs/installation

**Comment by madou** [comment]
are you using workspaces? can you talk through your repo setup

@pgmanutd 🤔 any ideas?

**Comment by pgmanutd** [comment]
strange 🤔 I just ran same in AF repo and its working. @alexreardon: Dumb question but `@compiled/react` package is present right? Because codemods are under `@compiled/react` only. As @madou asked, if possible can you talk through the repo setup?

**Comment by alexreardon** [comment]
Steps:

1. `yarn add @compiled/react`
2. add to `.babelrc`: `"plugins": ["@compiled/react/babel-plugin"]`
3. `npx @compiled/cli@latest`

> No codemods available right now.

My setup is extremely simple. A basic repo with no yarn workspaces etc

**Comment by madou** [comment]
ah i know why its broken. the CLI is looking in the wrong directory after the CJS change.

I'll fix and write a test.

**Comment by madou** [comment]
🤦 didn't fix it

**Comment by pgmanutd** [comment]
@madou: We can probably hardcode `@compiled/css` instead of reading from `pkgJson.name` in `export const COMPILED_IMPORT_PATH = pkgJson.name;`. Its better than hacky thing.

And fix is [here](https://github.com/atlassian-labs/compiled/blob/4943924324904beb8d3673a888d6bf3c4cce8a38/packages/cli/src/presets/codemods/utils/transforms.tsx#L8) 😅

**Comment by madou** [comment]
Yeah 😄 fix is small, I want to add some tests so it's harder for this to regress in the future. Will have a play and throw up a PR later 🤗

**Comment by madou** [comment]
This is fixed now. 

Run the CLI in your root of your repo and it will work:

```
npx @compiled/cli
```
