### ISSUE TITLE
Style object from other modules doesn't work

### ISSUE THREAD

**Issue by asvny** [atlassian-labs/compiled#494]
**Describe the bug**
Style object from other modules doesn't work

**To Reproduce**

```
// styles.ts
const root = {
 display: 'flex'
}

// component.ts
import { root } from './style.ts';

// No error and doesn't work (parcel)
<Heading css={root}>
```

**Expected behavior**
It should respect the style object from other modules

**Desktop (please complete the following information):**

- OS: Mac
- Browser chrome
- Version 87

**Additional context**

**Comment by madou** [comment]
Thanks for raising! Do you have compiled setup? For CSS prop to be enabled you need to import the react module, can you try doing this?

```tsx
import '@compiled/react';
import { root } from './style.ts';

<Heading css={root}>
```

**Comment by asvny** [comment]
I have a repo for this https://github.com/asvny/compiled-494
Looks like it works on the initial `yarn start` and then if I change the color value in `style.ts` file .. it doesn't reflect.

**Comment by madou** [comment]
Thanks!

That's a known bug at the moment https://github.com/atlassian-labs/compiled/issues/344 - it's a tricky problem. I'd imagine a bundler plugin could be written to ensure files are re-built when appropriate. If you have any thoughts in the area would love any insight 🙏

**Comment by asvny** [comment]
I am closing this issue in favor of #344
