### ISSUE TITLE
Next.js integration example

### ISSUE THREAD

**Issue by andreipfeiffer** [atlassian-labs/compiled#603]
**Is your feature request related to a problem? Please describe.**
I would like to include Compiled in my [CSS-in-TS analysis](https://github.com/andreipfeiffer/css-in-js).

**Describe the solution you'd like**
A working example with **Next.js** will greatly help.

**Describe alternatives you've considered**
I've searched for articles or any example, but couldn't find any.  
I've also searched the [Next.js examples](https://github.com/vercel/next.js/tree/canary/examples/) folder.

**Comment by madou** [comment]
Heya! Thanks for the issue

Can you add bespoke webpack plugins to next? You could try using the [webpack loader](https://compiledcssinjs.com/docs/pkg-webpack-loader)

**Comment by andreipfeiffer** [comment]
Yes, it is possible to add webpack plugins in Next.js.

However, I feel that there's more to that, regarding:
- code splitting
- SSR
- development vs production builds

Setting all these up requires a bit of understanding of how the library works under the hood.  


Other CSS-in-JS libraries either provide:
- a **Next.js plugin**
- or an **integration example**, typically in [Next.js examples](https://github.com/vercel/next.js/tree/canary/examples/) folder.

**Comment by madou** [comment]
That's fair!

Currently without the CSS extraction story (spike here: #561) you can actually just add the webpack plugin and all your points will work.

- code splitting (works because everything is JS)
- SSR (works the same as emotion SSR)
- dev vs. prod (works when building prod with `NODE_ENV=production`)
-

**Comment by andreipfeiffer** [comment]
Hey @madou thanks for the info, I'll give it a try then.

As a side note: what is the plan regarding CSS extraction? do you plan to ship it sometimes this year?

**Comment by madou** [comment]
Good luck! We are hoping to ship this year yes

**Comment by andreipfeiffer** [comment]
@madou one more thing:

When you say CSS extraction, do you mean:
1. Critical CSS extraction for SSR?
2. Static CSS files extraction, without runtime?

**Comment by madou** [comment]
The latter

**Comment by andreipfeiffer** [comment]
As I said, theoretically it's simple, but the devil is in the details :)  
I get a cryptic error, which seems to be thrown by webpack:

```
TypeError: this.getOptions is not a function
```

Apparently, there are a lot of such errors reported on the web, and it seems to be due to a breaking change in webpack versions: https://webpack.js.org/migrate/5/#getoptions-method-for-loaders

**What version of webpack** does your plugin supports?

**Comment by madou** [comment]
It supports v5

**Comment by madou** [comment]
I'll spend some time setting up an example, i'll put up a PR against next.

**Comment by madou** [comment]
I've updated compiled to work with v4 and also added a next example here https://github.com/vercel/next.js/pull/22786

👍 let me know how you go

**Comment by andreipfeiffer** [comment]
Hey @madou thanks a lot, man, I really appreciate the effort.

- I left you a comment on your PR
- I'll start my review today and let you know if I encounter any issues

**Comment by andreipfeiffer** [comment]
@madou there's only 1 thing I cannot figure out:

Is there any specific API or approach for defining global styles?
ie: styles for default `font-family`, for `html` or `body`

**Comment by andreipfeiffer** [comment]
@madou apart from the **global styles** question mentioned above, I have some more questions:

1. is Compiled **framework agnostic**? or React-only?
2. does it come with a built-in **theming system**?
3. using the **ClassNames** package (which apparently is also React specific) is the only option to get a string of CSS class names, right?

**Comment by madou** [comment]
Hello

> Is there any specific API or approach for defining global styles? ie: styles for default font-family, for html or body

not at this time https://github.com/atlassian-labs/compiled/issues/62

> is Compiled framework agnostic? or React-only?

react only for now.

> does it come with a built-in theming system?

not at this time https://github.com/atlassian-labs/compiled/issues/18

> using the ClassNames package (which apparently is also React specific) is the only option to get a string of CSS class names, right?

yes

**Comment by andreipfeiffer** [comment]
Hi @madou don't know where is best to post this, but here's the review on the library:
https://github.com/andreipfeiffer/css-in-js/blob/main/README.md#compiled

Thank you again for helping out with this.

**Comment by madou** [comment]
Thanks!

Re:

> bundles nested styles even if they are not used in component

What do you mean by this?

Also totally agree with the ClassNames component. I wrote up a thought here https://github.com/atlassian-labs/compiled/issues/618

**Comment by andreipfeiffer** [comment]
Regarding **unused bundle styles**, it's something that each library does one way or another (see the [`.unused_styles`](https://github.com/andreipfeiffer/css-in-js/blob/compiled/components/button.tsx#L76) nested rule, for example)

This is more prevalent in libraries that support any arbitrary nested selector, as it doesn't enforce good practices for scalable CSS, so anybody could add any nested rules, that the library doesn't check against the template to see if they really are used (I understand that it could be way too involved to do this, and in some case like **dynamic selectors** or certain **pseudos** it's practically impossible).

The only libraries that haven't seen to bundle nested styles are:
- **style9**
- **Tailwind** (which is not css-in-js, and it has no nesting)

I think I should probably move that bullet into the **Overall observations** section, as all libs have this behaviour.

**Comment by madou** [comment]
Sure! There is a strict mode we'd like to investigate later, see: #182 

Realistically though it would be an opt in thing. If we do it.

**Comment by andreipfeiffer** [comment]
Oohhh, very nice.

For backwards compatibility, you would probably have it opt-in, yes. However, if you implement such a feature, then:
- probably you would have a **mechanism to detect those rules** (in strict mode)
- with that in place, you **could/should throw some errors** (at built, or runtime) so the developer knows what's happening

Considering the above 2 statements, you could flip the logic:
- make it opt-out, enabled by default
- when you throw the error, you could point to the docs to tell the devs that if they need that feature, they can disable strict mode
- this way, you're promoting good practices, while also providing an escape hatch for those that understand the consequences

... just a thought.
