### ISSUE TITLE
Global styles component

### ISSUE THREAD

**Issue by madou** [atlassian-labs/compiled#62]
**API**

We will standardize on the `@emotion/react` API:

```jsx
import { Global } from '@compiled/react';

<Global 
  styles={{
    h1: { fontSize: 30 }
  }}
/>
```

**Assumptions**

- Dynamic declarations can't work with global styles
- Global styles will be extracted to an external stylesheet

**Outstanding questions**

- Do we force `@font-face` declarations to go through this component? Currently they can't be defined anywhere because it will blow up in prod mode
- How can we conditionally set global styles when they have been extracted to an external stylesheet? If there is no good story for this we may need to just not support this when baked as well.

**Comment by mhauens** [comment]
Is there already a way to add global CSS? Or can you recommend a workaround?

**Comment by madou** [comment]
Hi @mhauens there isn't a work around at the time unfortunately. We will be looking to implement this component in the next round of development (along side the ClassNames component, and keyframes api).

**Comment by madou** [comment]
@mhauens another alternative for global styles atm (won't work for SSR, unless you implement something yourself) 

```js
import { styled } from '@compiled/react';
import BodyClassName from 'react-body-classname';

export const DisableScroll = styled(BodyClassName)`
  overflow: hidden;
`;
```

When mounted will add class names to `body`. When unmounted will remove.

**Comment by madou** [comment]
I worked on a spike here for the global component https://github.com/atlassian-labs/compiled/pull/462. There are a few things that make it difficult because we want to be able to extract _everything_ to an external style sheet.

If we want to be able to extract all CSS, how can we fundamentally support _conditional_ global CSS? Aka, mount a component, styles are applied, unmount a component, styles are removed.

The solution is obvious if its purely a runtime one. It is complicated by extracting. Even more so that we want to support a runtime to extracted story over the lifecycle of compiled components. Fundamentally the answer could simply be - don't have conditional global styles! Without thinking on names:

- `PermanentGlobalStyles` component - for adding "always on" global styles
- `BrowserBodyStyles` component - for adding styles that can be "conditional" that only works on the browser, which adds it to the body element

But the downside is `PermanentGlobalStyles` goes against regular idiomatic React concepts. You could "unmount" the component and the styles wouldn't be removed.

One thing we could have in our tool belt is the conditionally render _style_ `link` elements, perhaps? https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link `disabled` attribute. However seemingly deprecated/not used now, so let's not.

What if we used `media` attributes instead? Or re-write the CSS to only apply given certain media queries or selectors. We'd want something that doesn't affect specificity though.

The downside would be after extracting we'd need applications to have a provider or something to render these links when appropriate, as well as support SSR story. Realistically we'd need that anyway for critical CSS.

**Comment by madou** [comment]
This is something that Compiled won't currently be supporting. Closing to clean up the issue list.
