### ISSUE TITLE
RFC: Third party PostCSS plugins

### ISSUE THREAD

**Issue by madou** [atlassian-labs/compiled#639]
Currently Compiled uses PostCSS to transform CSS at compile time. There is an opportunity to allow consumers of Compiled to apply their own plugins, with one constraint: You can't modify the generated atomic styles (more explicitly - generated class name hashes).

Why? Compiled exists to **support the wider _distributed_ ecosystem**. To support composition and conditional CSS one constraint is that the generated class names must be in a particular format. Because of that - we can't relinquish control of them.

So, the current thoughts are "custom" PostCSS plugins would run first, and then Compiled's. 

https://github.com/atlassian-labs/compiled/blob/master/packages/css/src/utils/css-transform.tsx#L25
```js
const sheets: string[] = [];
const classNames: string[] = [];

const result = postcss([
   // <-- Custom plugings here
  discardDuplicates(),
  parentOrphanedPseudos(),
```

**FAQ**

- "But your generated class names are too big!" I hear you think. It's true - we have an optimization idea here: https://github.com/atlassian-labs/compiled/issues/335

**Comment by pgmanutd** [comment]
I like this idea. I remember I said something about making our internal plugins configurable. But instead we can let consumers apply their own plugins and we can run ours later. We need to test this though.

**Comment by madou** [comment]
For now this is something we won't be implementing as a design decision. If you have any use cases for the need of this please raise a new issue.
