### ISSUE TITLE
@compiled/webpack-loader@0.6.10 doesn't include "extract.css"

### ISSUE THREAD

**Issue by jantimon** [atlassian-labs/compiled#666]
Sorry for not providing a pr - I couldn't see any build scripts in `@compiled/webpack-loader`..

I tried the extract feature and saw that https://unpkg.com/browse/@compiled/webpack-loader@0.6.10/css-loader/extract.css is missing from https://unpkg.com/browse/@compiled/webpack-loader@0.6.10/dist/compiled-loader.js

<img width="629" alt="UNPKG_-__compiled_webpack-loader" src="https://user-images.githubusercontent.com/4113649/112181130-6d7f2280-8bfc-11eb-83e5-a73e71ea1180.png">

**Comment by madou** [comment]
Thanks! I noticed too, I have a PR up 😅
