### ISSUE TITLE
Traverse module boundaries

### ISSUE THREAD

**Issue by madou** [atlassian-labs/compiled#67]
Right now we can parse the _typedefs_ using the code that already exists - but it isn't great. How should we move forward for this?

Import the code via `fs`, parse it with the project, and then continue on?

**Comment by madou** [comment]
This actually returns something:

```
import * as ts from 'typescript';
import * as fs from 'fs';

const transformerProgram = (program: ts.Program) => {
  const transformerFactory: ts.TransformerFactory<ts.SourceFile> = context => {
    return sourceFile => {
      const visitor = (node: ts.Node): ts.Node => {
        if (ts.isImportDeclaration(node) && ts.isStringLiteral(node.moduleSpecifier)) {
          const innerProgram = ts.createProgram([process.cwd() + '/node_modules/js-pkg/index.js'], {
            ...program.getCompilerOptions(),
            allowJs: true,
          });

          console.log(innerProgram.getSourceFile(process.cwd() + '/node_modules/js-pkg/index.js'));

          return node;
        }

        return ts.visitEachChild(node, visitor, context);
      };

      return ts.visitNode(sourceFile, visitor);
    };
  };

  return transformerFactory;
};
```

so im going to imagine we create a program inside if we:

1. find a js import
2. get `undefined` from the result of `typeChecker.getExportsOfModule(importSymbol)`

outstanding questions:

1. how do we reliably get the filename for a js import

**Comment by michalczukm** [comment]
Looks good to take 👍 
I can pick it up in a few days.

**Comment by madou** [comment]
dope, let me know how you go. put up something early if you can and let's talk about it

**Comment by michalczukm** [comment]
Long time, no see - I did some transformators while creating schematics for Angular.

I think that first point would be to create performance tests for this.
Do you have any suggestions, or an existing example of those kind of tests?
If not - I'll came with some suggestions.

I'll dive more into details in a few days, as I mentioned.

**Comment by madou** [comment]
awesome 😄 

> Do you have any suggestions, or an existing example of those kind of tests?

I don't! completely open to suggestions

thanks mate

**Comment by michalczukm** [comment]
I got more familiar with the repo today (you guys did a hell of a good and crazy work here 😄), and some help would be needed here 😅

The code snippet you added in https://github.com/atlassian-labs/compiled-css-in-js/issues/67#issuecomment-578493951 kind of mislead me. 

Few points I'd like to make sure of, please correct me if I'm wrong:

* in `/ts-transform/src/utils/collect-declarations.tsx` while we're collecting declarations current implementation doesn't support importing from plain .js file and while using Babel 👇

```typescript
// /babel-plugin/src/index.tsx
const stubProgam: ts.Program = ({
  getTypeChecker: () => ({
    getSymbolAtLocation: () => undefined,
  }),
} as never) as ts.Program;
```
* the snippet you added was suppose to run in those two scenarios, and get the declarations
* at the moment those scenarios are not covered at all

Still first thing I'd like to do is to provide some performance test, to make sure what will be the impact. 

I believe that you have some good examples you've used for manually testing hows the parsing works. Can you share those 😸  ?

**Comment by madou** [comment]
hi thanks!

1. correct we've nooped out the ts program so it can't get a hold of type checking.
2. thats correct - running with type checking off, and importing node modules dependencies
3. correct it just doesn't work - we can't traverse boundaries. this is primarily a problem when wanting to use other CSS

for fixing babel - we can always instantiate a real program and use that (which means typechecking is on!) and try to reuse the program for every file like https://github.com/dsherret/ts-morph does

it won't fix the problem of node modules though - we'll still need this work around for that.

for manually testing - maybe this? https://github.com/madou/typescript-transformer-handbook/blob/master/example-transformers/follow-node-modules-imports/transformer.ts

**Comment by madou** [comment]
Added in https://github.com/atlassian-labs/compiled/pull/266
