### ISSUE TITLE
Next.js class loading

### ISSUE THREAD

**Issue by visualcohol** [atlassian-labs/compiled#670]
**Describe the bug**
Compiled with Next.js class injection is not working as intended. After changing styled component css property, the change is not reflected in the browser.

**To Reproduce**

1. create a styles component
2. place it in the component
3. change the style of that component
4. the class name is applied but the class content does not exist

**Expected behavior**
After changing styled components css property the change should be reflected on the component

**Screenshots**
[Youtube link showing the issue](https://www.youtube.com/watch?v=lqq4pRHdcZE)

**Desktop (please complete the following information):**

- OS: [windows, windows WSL2]
- Browser [chrome, firefox]
- Version [10]

**Project dependencies**

- "@compiled/babel-plugin": "^0.6.9",
- "@compiled/react": "^0.6.8",
- "@compiled/webpack-loader": "^0.6.9",
- "babel-loader": "^8.2.2",
- "bootstrap": "^4.6.0",
- "next": "10.0.9",
- "react": "17.0.1",
- "react-dom": "17.0.1",
- "sass": "^1.32.8"

**Comment by madou** [comment]
Hey, thanks for raising this issue, are you using the Babel plugin or the
webpack loader?

**Comment by visualcohol** [comment]
I installed both:

"@compiled/babel-plugin": "^0.6.9",
"@compiled/react": "^0.6.8",
"@compiled/webpack-loader": "^0.6.9",

my next.config.js:
```
config.module.rules.push({
      test: /\.(js|ts|tsx)$/,
      exclude: /node_modules/,
      use: [
        {
          loader: 'babel-loader',
        },
        {
          loader: '@compiled/webpack-loader',
        },
      ],
    });
```

in .babelrc:

```
{
  "presets": ["next/babel"],
  "plugins": ["@compiled/babel-plugin"]
}

```

**Comment by madou** [comment]
Can you remove the Babel plugin in your babelrc and let me know how it goes?

**Comment by madou** [comment]
Here is a example in the nextjs repo
https://github.com/vercel/next.js/tree/canary/examples/with-compiled-css

**Comment by visualcohol** [comment]
My config now:

```
module.exports = {
  webpack: (config, options) => {
    // Note: we provide webpack above so you should not `require` it
    // Perform customizations to webpack config

    config.module.rules.push({
      test: /\.js$/,
      use: ['@compiled/webpack-loader'],
    });

    // Important: return the modified config
    return config;
  },
};
```
.babelrc:

```
{
  "presets": ["next/babel"],
  "plugins": ["@babel/plugin-syntax-jsx"]
}
```

Same issues

Pushed repo here:

[https://github.com/visualcohol/compiled-next](https://github.com/visualcohol/compiled-next)

**Comment by madou** [comment]
Thanks, I have a feeling this line of code might be affecting you https://github.com/atlassian-labs/compiled/blob/master/packages/react/src/runtime/style.tsx#L66

I'll do some investigation when I have a spare minute.

**Comment by madou** [comment]
Yep that's the problem, I'll put up a fix.

**Comment by madou** [comment]
Fixed in #672, will publish soon.

**Comment by madou** [comment]
Released in v

**Comment by visualcohol** [comment]
Thank you @madou, awesome work.
