### ISSUE TITLE
Unable to run with CRA and babel config

### ISSUE THREAD

**Issue by CarlosBalladares** [atlassian-labs/compiled#699]
**Describe the bug**

**To Reproduce**

1. Start a new application with create react app
2. install compiled and add a babel config
3. Implement a component and run start script

**Expected behavior**
The app should run.

**Screenshots**
![image](https://user-images.githubusercontent.com/14811752/113524616-ee83d580-957d-11eb-842f-82438bf81da8.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04
- Browser chrome
- Version N/A

**Comment by madou** [comment]
Hi there,

Unfortunately Compiled doesn't work with an unejected CRA at this point in time. One option is to eject and then configure the [webpack loader](https://compiledcssinjs.com/docs/installation#webpack).

Others could be using something like https://github.com/arackaf/customize-cra, but I haven't had any experience with them.

If you have any other thoughts please comment and we can talk through them 😄.

**Comment by CarlosBalladares** [comment]
Thanks @madou .I've seen some libraries offer out of the box support for cra and compiled css-in-js. The one I have in mind is https://github.com/CraigCav/css-zero is there any plans to achieve this? They do it using a babel macro. 

Thanks

**Comment by madou** [comment]
We can definitely try something to get it working like Craig did. 

@craigcav did you get sorting working as well? How do you order the style sheet post compilation/handle ordering split points?

**Comment by CraigCav** [comment]
css-zero doesn't attempt sorting/ordering of stylesheets/code split points. 

The naive approach I took in css-zero was to rewrite the inline styles to class names, write the extracted css file, then tack-on a css-modules import, allowing CRA's existing bundler support for css modules handle the rest.

**Comment by madou** [comment]
Thanks for replying 🙏 

Hmmm we could do that too, but it would mean some styles won't be stable when extracted... 🤔

**Comment by CraigCav** [comment]
While extraction would be great, CRA support for the "baked" version would be a good start (assuming this isn't supported already). That would give folks the option to started with CRA and eject and extract when they're ready to optimize.

**Comment by madou** [comment]
Fair point, which would definitely work!
