### ISSUE TITLE
Benchmarks aren't functional

### ISSUE THREAD

**Issue by MatthewCharlton** [atlassian-labs/compiled#719]
**Describe the bug**
When you run ```yarn benchmark:ssr``` you get compilation errors due to Type issues. Even after resolving these I found `ts-node` seems to throw when parsing ```packages/react/dist/cjs/runtime.js```.

**Expected behavior**
The library should be compiled successfully and the benchmarks should run.

**Screenshots**
<img width="781" alt="Screen Shot 2021-04-06 at 10 11 49 am" src="https://user-images.githubusercontent.com/33848730/113641199-825dba80-96c0-11eb-9ffa-f8dd780efb1e.png">

**Desktop (please complete the following information):**
- OS: OSX v10.15.7 - MacBook Pro

**Testing notes**

- Benchmarks test all current runtime APIs in the browser
- Benchmarks test all current runtime APIs in the server
- Benchmarks run in CI
- Benchmarks compare themselves to `master` in pull requests and comments on PRs with timings, and difference (follow up PR, but at least do research into how we can have this done)

**Comment by madou** [comment]
Added some testing notes to the description.

**Comment by madou** [comment]
This has been fixed in #920
