### ISSUE TITLE
[Webpack] Code split CSS

### ISSUE THREAD

**Issue by madou** [atlassian-labs/compiled#722]
Currently CSS extraction forces all styles to be inside one style sheet to simplify the first implementation. Ideally, we want to be able to only load the CSS that is used instead of downloading it all, however there are some constraints:

1. Unsafe atomic styles need to be hoisted to the top entry point
2. All style sheets need to be sorted

When we say unsafe atomic styles, we're primarily talking about pseudo styles defined here https://compiledcssinjs.com/docs/atomic-css#automatic-pseudo-class-ordering.

**Why do they need to be hoisted?**

If we don't the order of applied styles won't be consistent, resulting in different experiences depending what chunks were loaded and when. We want to avoid that at all costs.

**Comment by madou** [comment]
There is a spike put up in https://github.com/atlassian-labs/compiled/pull/724 that could be used as a starting point for anyone picking this up.

**Comment by JakeLane** [comment]
Ideally, we should not implement this as atomic styles should allow enough rule reuse to utilise a single sheet.

We can revisit this later if this assumption does not pan out.
