### ISSUE TITLE
RFC: Replace static evaluation with evaluated at build time

### ISSUE THREAD

**Issue by madou** [atlassian-labs/compiled#723]
We write a lot of code in Compiled to statically evaluate CSS. And I mean a lot of code. I don't think we can reliably continue down this to get worthwhile ROI for it, even though it "feels best", as there are countless edge cases we need to handle, and will need to handle in the future as the library rolls out. What's worse is its not portable, so if we were to keep investing in this area, when we move to a newer bundler (e.g. esbuild) we'd have to throw the code away (or re-use it inside esbuild, but that would only be an interim solution).

As far as I know we're the only compile time library to statically evaluate, others have either not done it at all, or have gone down the path of evaluating at build time.

- Treat
- Vanilla Extract
- Linaria

Are examples of libraries which evaluate at build time (read: execute the code during a build step and then use the result for whatever is needed).

Current entry point for static evaluation is here https://github.com/atlassian-labs/compiled/blob/master/packages/babel-plugin/src/utils/evaluate-expression.tsx#L329 -- note we wouldn't be _completely_ getting rid of static evaluation, at least in the first pass, it would only be for nodes we're interested in evaluating (not the entire file).

**Comment by layershifter** [comment]
@madou our Babel plugin for `@fluentui/make-styles` also uses combined approach for evaluation, https://github.com/microsoft/fluentui/blob/84296aa8db9ddbf0250f24703fb304c360ff05e1/packages/babel-make-styles/src/utils/evaluatePaths.ts#L16-L31.

- if we can - statically evaluate with Babel]
- if we can't - use evaluation during build time, https://github.com/microsoft/fluentui/blob/84296aa8db9ddbf0250f24703fb304c360ff05e1/packages/babel-make-styles/src/utils/evaluatePathsInVM.ts#L129-L134

---

I decided to not invent wheel and reuse the solution from Linaria:
- `@linaria/babel-preset` contains `Module` to actually evaluate code, https://github.com/microsoft/fluentui/blob/84296aa8db9ddbf0250f24703fb304c360ff05e1/packages/babel-make-styles/src/utils/evaluatePathsInVM.ts#L35-L39
- `@linaria/shaker` is one of possible evaluators (transformers) that removes unused code/imports to evaluate less code

**Comment by madou** [comment]
Closing this for now.
