### ISSUE TITLE
RFC: Ensuring an incremental migration path to future major versions

### ISSUE THREAD

**Issue by madou** [atlassian-labs/compiled#730]
New major versions will come eventually - we want to ensure that we can migrate without much pain. Compiled should function with the previous (1) major version.

**Example scenario**

1. platform upgrades
2. product upgrades platform packages
3. product now using multiple major versions of Compiled
4. product eventually upgrades

**Ensured stability**

Upgrading between major versions should ensure:

1. style composition
2. style extraction

Still function as expected.

**Features that could break**

1. Changing hash of [atomic group](https://github.com/atlassian-labs/compiled/blob/68e7fc51de9fe7155bab5ad0221ec975791bf8ed/packages/css/src/plugins/atomicify-rules.tsx#L28)
2. Changing hash of [atomic value](https://github.com/atlassian-labs/compiled/blob/68e7fc51de9fe7155bab5ad0221ec975791bf8ed/packages/css/src/plugins/atomicify-rules.tsx#L29)
3. Baked API changing resulting in breaking CSS extraction
4. Baked style ordering
5. ... more here

**Comment by marcodejongh** [comment]
Isn't the idea that with compiled, the CSS is compiled in, and as a result, there's no runtime dependency; thus, dependency mismatching shouldn't occur?
Or is this a problem specific to style extraction?

**Comment by madou** [comment]
There's always things that can break stuff, just because it's extracted doesn't mean it won't break 😅

Compiled still has a runtime dependency, its just a minimal one.

**Comment by madou** [comment]
Closing this issue as it has served its purpose.
