### ISSUE TITLE
Compiled is not adding the key attribute

### ISSUE THREAD

**Issue by youzi** [atlassian-labs/compiled#802]
**Describe the bug**
Consider this component:
```
import '@compiled/react'

const MyComponent = () => {
  return ['foo', 'bar'].map((string) => {
    return (
      <div key={string} css={{ backgroundColor: 'blue' }}>
        {string}
      </div>
    )
  })
}
```

Rendering this component results in the following warning: `Warning: Each child in a list should have a unique "key" prop.`

It seems that the key prop is not added to the element that the library is adding.

**To Reproduce**
See example above

Note: I'm using the following versions:
```
"@compiled/react": "^0.6.13",
"@compiled/babel-plugin": "^0.6.14"
```

**Comment by JakeLane** [comment]
Hi @youzi please update to the [newest version](https://github.com/atlassian-labs/compiled/releases/tag/%40compiled%2Fbabel-plugin%400.7.0) for the fix
