### ISSUE TITLE
Add eslint rules to reduce bikeshedding

### ISSUE THREAD

**Issue by JakeLane** [atlassian-labs/compiled#828]
Dev loop could be improved by adding a few new rules to reduce bikeshedding on PRs.

- [Consistent type imports](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/consistent-type-imports.md)

**Comment by madou** [comment]
Nice! What are you thinking? We have a load of techstack rules inside Atlassian Frontend that you could consider as well.

**Comment by JakeLane** [comment]
Sorry @madou , missed this when merging https://github.com/atlassian-labs/compiled/pull/833
