### ISSUE TITLE
Compiled + NextJS doesn't support path aliases

### ISSUE THREAD

**Issue by madeleineostoja** [atlassian-labs/compiled#843]
**Describe the bug**
I have several path aliases (eg: `$components/...`) setup in my NextJS project in my `tsconfig.json`, which Next automatically supports and I assume injects into Webpack aliases.

Compiled does not support these for some reason, and complains that it can't find a module when using them.

**To Reproduce**

1. Add `@compiled/webpack-loader` to Webpack rules in `next.config.js`
2. Setup path aliases in `tsconfig`/`jsconfig`
3. Try import a const using the `css` tagged template for Compiled
4. See `Cannot find module...` error

**Expected behavior**
Compiled should support Webpack/NextJS aliases 

**Screenshots**

<img width="347" alt="Screen Shot 2021-10-03 at 7 47 10 PM" src="https://user-images.githubusercontent.com/6374876/135743239-4304d0cf-b595-42fc-a982-844aaea83482.png">

**Desktop (please complete the following information):**

- OS: [e.g. iOS] macOS
- Browser [e.g. chrome, safari] N/A

**Comment by venkat1702** [comment]
Hi @MonicaOlejniczak, thank you for the fix, I tried adding the alias in the `webpack-loader`'s **resolve** option, but I am still getting the same error. Can you please provide an example for the declaring the alias in a way that compiled module understands?
