### ISSUE TITLE
Is Compiled supported by Atlassian?

### ISSUE THREAD

**Issue by madeleineostoja** [atlassian-labs/compiled#889]
Bit of a random one, but is Compiled used internally/backed by Atlassian? Or is it a side project by some folks that work there?

I’m evaluating & advocating for Compiled at both my agency and a product I’m working on, and since it’s a fairly young project knowing it has legs re: future maintenance would really help my case vs the no-brainers like Emotion.

**Comment by JakeLane** [comment]
Hi @madeleineostoja, at the moment Compiled is now in active development for adoption by our products. It's not currently in production but we're in the process of migration right now.

**Comment by madeleineostoja** [comment]
Amazing thanks @JakeLane! Sounds super promising, and that gives me the peace of mind to do a spike on it and then advocate for adoption ourselves
