### ISSUE TITLE
Bump jscodeshift to ^0.13.0

### ISSUE THREAD

**Issue by DarkPurple141** [atlassian-labs/compiled#896]
The recent `jscodeshift` major version means this dependency can't be deduped in the AFP monorepo.

Ideally this is bumped so we can dedupe!

**Comment by JakeLane** [comment]
Already merged - just need to release the changes ⚡ https://github.com/atlassian-labs/compiled/pull/885

**Comment by DarkPurple141** [comment]
@JakeLane thanks mate!
