### ISSUE TITLE
Loading imported 'images' using babel loader

### ISSUE THREAD

**Issue by onionhammer** [atlassian-labs/compiled#956]
**Describe the bug**
When adding an image in React, I receive the following error:

```
Property expression of ExpressionStatement expected node to be of a type ["Expression"] but instead got "ImportDefaultSpecifier"
```

**To Reproduce**
- Create React App with craco
- New dependencies
    "@compiled/babel-plugin": "^0.11.1",
    "@compiled/react": "^0.10.0",
- Import an image and try to create a style to use the image
 ```tsx
 import dropdownSvg from './Dropdown.svg'; 

export const Select = styled.select({
    background: `#fff no-repeat center right .5rem`,
    backgroundImage: `url(${dropdownSvg})`,
});

```

**Expected behavior**
dropdownSvg is a string with a path in the /static/media folder, backgroundImage should be assigned that path

Additionally, some way to include imported images should be documented, currently there's basically no reference to using images in the docs that I can find

**Comment by onionhammer** [comment]
Workaround:

Passing image as a prop works; 


import dropdownSvg from './Dropdown.svg';

export const Select = styled.select<{ bgImage?: string }>({
    ...sharedInput,
    background: `#fff no-repeat center right .5rem`,
    backgroundImage: props => `url(${props.bgImage})`,
});

Select.defaultProps = {
    bgImage: dropdownSvg,
};

**Comment by JakeLane** [comment]
thanks for reporting and the workaround @onionhammer! We'll take a look in the next few days

**Comment by JakeLane** [comment]
It looks like we need to add handling for file imports in our static evaluation. I'll add functionality to the plugin to take in config for supported extensions and investigate automating this with the webpack/parcel loaders.
