### ISSUE TITLE
TypeScript 'nested rules' broken

### ISSUE THREAD

**Issue by onionhammer** [atlassian-labs/compiled#958]
**Describe the bug**
When adding "&:hover" to a css({}) object, typescript blows up

      Object literal may only specify known properties, and '"&:hover"' does not exist in type 'Properties<BasicTemplateInterpolations, string & {}>'.  TS2769

![image](https://user-images.githubusercontent.com/969938/144468990-d01dbf36-efa3-4b47-b093-939e14cd2c12.png)

**To Reproduce**
```tsx
const largeText = css({
  fontSize: "40px",
  color: "black",

  "&:hover": {
    color: "red"
  }
});
```

**Workaround**
Add // @ts-expect-error above css

**Additional context**
Using CRACO and create-react-app with 

```js
module.exports = {
    babel: {
        plugins: [
            ["@compiled/babel-plugin", { cache: true, importReact: false }],
        ]
    },
}
```

Edit: this seems bigger than just pseudo-selectors, typescript doesnt like any nested selectors

https://compiledcssinjs.com/docs/writing-css#nested-rules

**Comment by onionhammer** [comment]
Monkey patching pseudo-selectors into types.d.ts would kind of do the trick

![image](https://user-images.githubusercontent.com/969938/144470189-4e8e66e9-680c-4867-b830-65f601f4954b.png)

**Comment by pancaspe87** [comment]
Hi @onionhammer, 
thanks for reporting the bug. We were not able to replicate it; it may have been fixed by the recent releases. Is it still happening on your end?

cc @wilsonhou

**Comment by onionhammer** [comment]
@pancaspe87 No more, will close assuming it's fixed
